version: '3.4'

services:
    php:
        image: ghcr.io/ngrie/rtmpie/php:latest
        environment:
            APP_SECRET: ${RTMPIE_APP_SECRET}
            DATABASE_URL: mysql://root:${RTMPIE_DATABASE_PASSWORD}@database:3306/rtmpie?serverVersion=mariadb-10.4.12
            MERCURE_PUBLIC_URL: ${RTMPIE_HTTP_SCHEME}://${RTMPIE_HOSTNAME}/.well-known/mercure
            MERCURE_JWT_SECRET: ${RTMPIE_MERCURE_JWT_KEY}

    caddy:
        image: ghcr.io/ngrie/rtmpie/caddy:latest
        ports:
            - 80:80
            - 443:443
        environment:
            SERVER_NAME: ${RTMPIE_CADDY_SERVER_NAME}
            MERCURE_PUBLISHER_JWT_KEY: ${RTMPIE_MERCURE_JWT_KEY}
            MERCURE_SUBSCRIBER_JWT_KEY: ${RTMPIE_MERCURE_JWT_KEY}
        volumes:
            - mercure_data:/data
            - mercure_config:/config

    rtmp:
        image: ghcr.io/ngrie/rtmpie/rtmp:latest
        ports:
            - 1935:1935

    database:
        image: mariadb:10.4
        environment:
            MYSQL_ROOT_PASSWORD: ${RTMPIE_DATABASE_PASSWORD}
            MYSQL_DATABASE: rtmpie
        volumes:
            - database:/var/lib/mysql

volumes:
    database:
    mercure_data:
    mercure_config:
